package plausibcheck.adress

import com.ruiger.hello.pojo.Risklibrary;
import com.ruiger.hello.pojo.Issuepointtransitiondetail;
import com.ruiger.hello.pojo.ResultCheck;


rule "issue point number must less than 100"

    when
        $riskType : Risklibrary();
        issuePoint : Issuepointtransitiondetail(issuepointnum < $riskType.getRiskvalue())
        checkResult : ResultCheck();
    then
        checkResult.setPass(true);
        System.out.println("规则中打印日志：校验通过!");
end

rule "issue point number must more than 100"

    when
        $riskType : Risklibrary(riskvalue>"1");
                issuePoint : Issuepointtransitiondetail(issuepointnum >= $riskType.getRiskvalue())
        checkResult : ResultCheck();
    then
        checkResult.setPass(false);
        System.out.println("分数预警！！！！！");
end